== Gradle DSL

* Underlying language is Groovy
* You don't need to be a Groovy expert to be a Gradle power user
* Groovy doesn't need `;` in most cases
* Groovy does more with less punctuation, making it an ideal choice for a DSL
* In most cases lines that do not end on an operator is considered a completed statement.

=== Groovy vs Java

In Groovy:

* All class members are public by default
* No need to create getters/setters for public fields
* Both static & dynamic typing supported
* `def` means `Object`

=== Calling Methods

[source,groovy]
----
class Foo {
  void bar( def a,def b ) {}
}

def foo = new Foo()

foo.bar( '123',456 )
foo.bar '123', 456

foo.with {
  bar '123', 456
}
----

=== Calling Methods with Closures

[source,groovy]
----
class Foo {
  void bar( def a,Closure b ) {}
}

def foo = new Foo()

foo.bar( '123',{ println it } )

foo.bar ('123') {
  println it
}

foo.bar '123', {
  println it
}
----

=== Maps in Groovy

Hashmaps in Groovy are simple to use

[source,groovy]
----
def myMap = [ plugin : 'java' ]
----

Maps are easy to pass inline to functions

[source,groovy]
----
project.apply( plugin : 'java' )
----

Which in Gradle can become

[source,groovy]
----
apply plugin : 'java'
----

=== Lists in Groovy

* Lists in Groovy are simple too
[source,groovy]
----
def myList = [ 'clone', ''http://github.com/ysb33r/GradleLectures' ]
----

* This makes it possible for Gradle to do

[source,groovy]
----
args 'clone', 'http://github.com/ysb33r/GradleLectures'
----

=== Closure Delegation in Groovy

* When a symbol cannot be resolved within a closure, Groovy will look elsewhere
* In Groovy speak this is called a *Delegate*.
* This can be programmatically controlled via the `Closure.delegate` property.

=== Closure Delegation in Groovy

[source,groovy]
----
class Foo {
  def target
}

class Bar {
  Foo foo = new Foo()
  void doSomething( Closure c ) {
    c.delegate = foo
    c()
  }
}

Bar bar = new Bar()
bar.doSomething {
  target = 10
}
----

=== More Closure Magic

If a Groovy class has a method 'call(Closure)`, the object can be passed a closure directly.

[source,groovy]
----
class Foo {
  def call( Closure c) { /* ... */ }
}

Foo foo = new Foo()
foo {
  println 'Hello, world'
}

// This avoids ugly syntax
foo.call({ println 'Hello, world' })
----

=== Closure Delegation in Gradle

* In most cases the delegation will be entity the closure is passed to.
* Will also look at the `Project` and `ext` objects.
* The `Closure.delegate` property allows plugin writers ability to create beautiful DSLs

[source,groovy]
----
task runSomething(type : Exec ) { cmdline 'git' }
----

is roughly the equivalent of

[source,groovy]
----
ExecTask runSomething = new ExecTask()
runSomething.cmdline( 'git' )
----
